export const properties = [
  {
    id: '1',
    title: 'Luxury Penthouse at Palm Jumeirah',
    location: 'Palm Jumeirah, Dubai',
    area: 'Palm Jumeirah',
    type: 'Penthouse',
    bedrooms: 4,
    bathrooms: 5,
    guests: 8,
    sqft: 5500,
    price: 4500,
    rating: 4.9,
    reviews: 127,
    isElite: true,
    amenities: ['Private Pool', 'Ocean View', 'Smart Home', 'Private Beach', 'Gym', 'Spa'],
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    description: 'Experience ultimate luxury in this stunning penthouse with panoramic views of the Arabian Gulf.',
  },
  {
    id: '2',
    title: 'Modern Villa in Emirates Hills',
    location: 'Emirates Hills, Dubai',
    area: 'Emirates Hills',
    type: 'Villa',
    bedrooms: 6,
    bathrooms: 7,
    guests: 12,
    sqft: 12000,
    price: 8500,
    rating: 4.95,
    reviews: 89,
    isElite: true,
    amenities: ['Private Pool', 'Golf Course View', 'Smart Home', 'Cinema Room', 'Gym', 'Garden'],
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    description: 'A magnificent villa nestled in the prestigious Emirates Hills with stunning golf course views.',
  },
  {
    id: '3',
    title: 'Burj Khalifa View Apartment',
    location: 'Downtown Dubai',
    area: 'Downtown',
    type: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    sqft: 1800,
    price: 1800,
    rating: 4.8,
    reviews: 234,
    isElite: false,
    amenities: ['Burj Khalifa View', 'Pool Access', 'Gym', 'Concierge', 'Parking'],
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    ],
    description: 'Wake up to breathtaking views of the world\'s tallest building in this modern apartment.',
  },
  {
    id: '4',
    title: 'Marina Waterfront Suite',
    location: 'Dubai Marina',
    area: 'Dubai Marina',
    type: 'Apartment',
    bedrooms: 3,
    bathrooms: 3,
    guests: 6,
    sqft: 2400,
    price: 2200,
    rating: 4.85,
    reviews: 156,
    isElite: true,
    amenities: ['Marina View', 'Pool', 'Gym', 'Beach Access', 'Concierge', 'Parking'],
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
    ],
    description: 'Enjoy the vibrant Marina lifestyle in this elegant waterfront suite.',
  },
  {
    id: '5',
    title: 'Beachfront Villa JBR',
    location: 'Jumeirah Beach Residence',
    area: 'JBR',
    type: 'Villa',
    bedrooms: 5,
    bathrooms: 6,
    guests: 10,
    sqft: 8000,
    price: 6500,
    rating: 4.92,
    reviews: 78,
    isElite: true,
    amenities: ['Private Beach', 'Pool', 'BBQ Area', 'Smart Home', 'Gym', 'Staff Quarters'],
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    description: 'Direct beach access and stunning sea views from this exclusive JBR villa.',
  },
  {
    id: '6',
    title: 'City Walk Luxury Loft',
    location: 'City Walk, Dubai',
    area: 'City Walk',
    type: 'Loft',
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    sqft: 1200,
    price: 950,
    rating: 4.7,
    reviews: 312,
    isElite: false,
    amenities: ['City View', 'Pool', 'Gym', 'Near Mall', 'Parking'],
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    description: 'A stylish urban retreat in the heart of Dubai\'s trendiest neighborhood.',
  },
]

export const areas = [
  'Palm Jumeirah',
  'Downtown',
  'Dubai Marina',
  'Emirates Hills',
  'JBR',
  'City Walk',
  'Business Bay',
  'DIFC',
]

export const propertyTypes = ['Villa', 'Penthouse', 'Apartment', 'Loft', 'Townhouse']

export const amenitiesList = [
  'Private Pool',
  'Ocean View',
  'Smart Home',
  'Private Beach',
  'Gym',
  'Spa',
  'Golf Course View',
  'Cinema Room',
  'Garden',
  'Concierge',
  'Parking',
  'BBQ Area',
]

export const conciergeServices = [
  {
    id: 'airport-transfer',
    name: 'Airport Transfer',
    description: 'Luxury car pickup from Dubai International Airport',
    price: 350,
    icon: 'Plane',
  },
  {
    id: 'private-chef',
    name: 'Private Chef',
    description: 'Personal chef for an exclusive dining experience',
    price: 1500,
    icon: 'ChefHat',
  },
  {
    id: 'yacht-charter',
    name: 'Yacht Charter',
    description: 'Private yacht experience in Dubai Marina',
    price: 5000,
    icon: 'Ship',
  },
  {
    id: 'spa-service',
    name: 'In-Villa Spa',
    description: 'Professional spa treatments at your villa',
    price: 800,
    icon: 'Sparkles',
  },
  {
    id: 'car-rental',
    name: 'Luxury Car Rental',
    description: 'Drive a premium vehicle during your stay',
    price: 1200,
    icon: 'Car',
  },
  {
    id: 'cleaning',
    name: 'Daily Cleaning',
    description: 'Professional housekeeping service',
    price: 200,
    icon: 'SprayCan',
  },
]

export const maintenanceTickets = [
  {
    id: 'T001',
    property: 'Luxury Penthouse at Palm Jumeirah',
    issue: 'AC not cooling properly',
    priority: 'high',
    status: 'in-progress',
    assignedTo: 'Ahmed Hassan',
    createdAt: '2024-01-10',
    updatedAt: '2024-01-11',
  },
  {
    id: 'T002',
    property: 'Marina Waterfront Suite',
    issue: 'Leaking faucet in master bathroom',
    priority: 'medium',
    status: 'pending',
    assignedTo: 'Unassigned',
    createdAt: '2024-01-11',
    updatedAt: '2024-01-11',
  },
  {
    id: 'T003',
    property: 'Burj Khalifa View Apartment',
    issue: 'Smart lock battery replacement',
    priority: 'low',
    status: 'completed',
    assignedTo: 'Mohammed Ali',
    createdAt: '2024-01-08',
    updatedAt: '2024-01-09',
  },
]

export const bookings = [
  {
    id: 'B001',
    propertyId: '1',
    property: 'Luxury Penthouse at Palm Jumeirah',
    guest: 'John Smith',
    checkIn: '2024-01-15',
    checkOut: '2024-01-22',
    status: 'confirmed',
    total: 31500,
  },
  {
    id: 'B002',
    propertyId: '3',
    property: 'Burj Khalifa View Apartment',
    guest: 'Sarah Johnson',
    checkIn: '2024-01-18',
    checkOut: '2024-01-25',
    status: 'pending',
    total: 12600,
  },
  {
    id: 'B003',
    propertyId: '4',
    property: 'Marina Waterfront Suite',
    guest: 'Michael Brown',
    checkIn: '2024-01-20',
    checkOut: '2024-01-27',
    status: 'confirmed',
    total: 15400,
  },
]

export const ownerStats = {
  totalEarnings: 245000,
  monthlyEarnings: 78500,
  occupancyRate: 87,
  averageRating: 4.85,
  totalBookings: 34,
  upcomingBookings: 5,
  expenses: {
    maintenance: 12500,
    cleaning: 8400,
    utilities: 4200,
    management: 24500,
  },
  monthlyData: [
    { month: 'Jul', earnings: 62000, occupancy: 82 },
    { month: 'Aug', earnings: 71000, occupancy: 89 },
    { month: 'Sep', earnings: 58000, occupancy: 75 },
    { month: 'Oct', earnings: 67000, occupancy: 81 },
    { month: 'Nov', earnings: 82000, occupancy: 92 },
    { month: 'Dec', earnings: 95000, occupancy: 98 },
  ],
}

export const assets = [
  {
    id: 'A001',
    name: 'Samsung 75" Smart TV',
    property: 'Luxury Penthouse at Palm Jumeirah',
    category: 'Electronics',
    purchaseDate: '2023-06-15',
    warrantyExpiry: '2026-06-15',
    status: 'good',
    value: 8500,
  },
  {
    id: 'A002',
    name: 'Miele Washing Machine',
    property: 'Marina Waterfront Suite',
    category: 'Appliances',
    purchaseDate: '2023-03-20',
    warrantyExpiry: '2025-03-20',
    status: 'good',
    value: 6200,
  },
  {
    id: 'A003',
    name: 'Italian Leather Sofa Set',
    property: 'Emirates Hills Villa',
    category: 'Furniture',
    purchaseDate: '2022-11-10',
    warrantyExpiry: '2024-11-10',
    status: 'needs-attention',
    value: 45000,
  },
]

export const inspectionChecklist = [
  { id: 1, category: 'Living Area', item: 'Sofa and cushions clean and intact', checked: false },
  { id: 2, category: 'Living Area', item: 'TV and remote functioning', checked: false },
  { id: 3, category: 'Living Area', item: 'Air conditioning working properly', checked: false },
  { id: 4, category: 'Kitchen', item: 'All appliances functioning', checked: false },
  { id: 5, category: 'Kitchen', item: 'Utensils complete and clean', checked: false },
  { id: 6, category: 'Kitchen', item: 'Refrigerator clean and empty', checked: false },
  { id: 7, category: 'Bedroom', item: 'Bed linens fresh and clean', checked: false },
  { id: 8, category: 'Bedroom', item: 'Wardrobe empty and clean', checked: false },
  { id: 9, category: 'Bathroom', item: 'Toiletries restocked', checked: false },
  { id: 10, category: 'Bathroom', item: 'Towels fresh and complete', checked: false },
  { id: 11, category: 'Bathroom', item: 'No plumbing issues', checked: false },
  { id: 12, category: 'Security', item: 'Smart lock functioning', checked: false },
  { id: 13, category: 'Security', item: 'Safe empty and reset', checked: false },
  { id: 14, category: 'General', item: 'No damage to walls/floors', checked: false },
  { id: 15, category: 'General', item: 'All lights working', checked: false },
]
